# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ef52599a8dfe0b1063455298e504ff02fefd66ddaf450693bf60490adf8719300113f1d69cf33b3ce0715816a337e01f33cdb3645977cf0946ad5360c456934

test:
  secret_key_base: 1a1448c47af24c73fe091a4bc46b46a6458c1660d95db68b9383db2b735ff011bea2671ac7e7fc31da18292a2d643a0141ae76c4f86d4eb6819b6de2c4cb4893

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
